---
apiVersion: v1
kind: ConfigMap
metadata:
  name: policy-advisor-config
data:
  config.yaml: |
    ####################################
    # K8s Policy Advisor Daemon Config
    ####################################
    api.enabled: true
    api.endpoint: "0.0.0.0"
    api.port: "8176"
    api.readTimeout: "5s"
    api.stopTimeout: "5s"

    backend.url: "http://sysdigcloud-api:8080"
    backend.tlsCheckCertificate: true

    mysql.username: "padvisor"
    mysql.database: "padvisor"
    mysql.host: "sysdigcloud-mysql"
    mysql.port: "3306"

    log.level: "INFO"
